package ch8java6thedition;

/**
 * 11. First to One Game
 * 
 * This game is meant for two or more players. In the game, 
 * each player starts out with 50 points, as each player takes
 * a turn rolling the dice; the amount generated by the dice 
 * is subtracted from the player's total. The first player with 
 * exactly one point remaining wins. If a player's remaining 
 * points minus the amount generated by the dice results in a 
 * value less than one, then the amount should be added to the 
 * player's points. (As an alternative, the game can be played 
 * with a set number of turns. In this case, the player with 
 * the number of points closest to one, when all rounds have 
 * been played, wins.)
 * 
 * Write a program that simulates the game being played by two
 * players. Use the Die class that was presented in Chapter 6
 * to simulate the dice. Write a player class to simulate the 
 * players.
 * 
 * @author craig
 * 2-9-21
 * 8:20pm
 */
public class FirstToOne {
	public static void main(String[]args) {
		int player1Points = 50;
		int player2Points = 50;
		int roll1 = 0;
		int roll2 = 0;

		// Create two player objects
		Player player1 = new Player();
		Player player2 = new Player();

		// Create two die
		DieRoller die = new DieRoller(6);

		// Loop to roll till someone wins
		while(!(player1.getPoints() == 1) && !(player2.getPoints() == 1)) {

			roll1 = (die.roll() + die.roll());
			
			if((player1Points -= roll1) < 1) {
				player1Points += roll1;
			}
			else
				player1Points -= roll1;
			
			System.out.println("Player 1 rolled " + roll1 + 
				" and now has " + player1Points);

			if(player1Points == 1) 
				break;

			roll2 = die.roll() + die.roll();
			player2Points -= roll2;

			if((player2Points -= roll2) < 1) {
				player2Points += roll2;
			}
			else
				player1Points -= roll2;

			System.out.println("Player 2 rolled " + roll2 + 
				" and now has " + player2Points);

			if(player2Points == 1) 
				break; 

			System.out.println("\n");
		}

		if(player1Points == 1) {
			System.out.println("Player 1 wins!");
		}
		else if (player2Points == 1) {
			System.out.println("Player 2 wins!");
		}
	}	
}
